/* tslint:disable */
/* eslint-disable */
/**
 * JS-SS21 API Documentation
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface University
 */
export interface University {
    /**
     * 
     * @type {string}
     * @memberof University
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof University
     */
    homepage: string;
}

export function UniversityFromJSON(json: any): University {
    return UniversityFromJSONTyped(json, false);
}

export function UniversityFromJSONTyped(json: any, ignoreDiscriminator: boolean): University {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'homepage': json['homepage'],
    };
}

export function UniversityToJSON(value?: University | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'homepage': value.homepage,
    };
}


