/* tslint:disable */
/* eslint-disable */
/**
 * JS-SS21 API Documentation
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Address,
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
} from './';

/**
 * 
 * @export
 * @interface CompanyDto
 */
export interface CompanyDto {
    /**
     * address field
     * @type {Address}
     * @memberof CompanyDto
     */
    address: Address;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    companyProfileImageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    companyHeaderImageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    companyInfo: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyDto
     */
    homepage?: string;
}

export function CompanyDtoFromJSON(json: any): CompanyDto {
    return CompanyDtoFromJSONTyped(json, false);
}

export function CompanyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': AddressFromJSON(json['address']),
        'email': json['email'],
        'name': json['name'],
        'companyProfileImageUrl': json['companyProfileImageUrl'],
        'companyHeaderImageUrl': json['companyHeaderImageUrl'],
        'companyInfo': json['company_info'],
        'homepage': !exists(json, 'homepage') ? undefined : json['homepage'],
    };
}

export function CompanyDtoToJSON(value?: CompanyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': AddressToJSON(value.address),
        'email': value.email,
        'name': value.name,
        'companyProfileImageUrl': value.companyProfileImageUrl,
        'companyHeaderImageUrl': value.companyHeaderImageUrl,
        'company_info': value.companyInfo,
        'homepage': value.homepage,
    };
}


