/* tslint:disable */
/* eslint-disable */
/**
 * JS-SS21 API Documentation
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleSavedJobsResponse
 */
export interface ToggleSavedJobsResponse {
    /**
     * 
     * @type {string}
     * @memberof ToggleSavedJobsResponse
     */
    action: ToggleSavedJobsResponseActionEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ToggleSavedJobsResponse
     */
    ok: boolean;
}

/**
* @export
* @enum {string}
*/
export enum ToggleSavedJobsResponseActionEnum {
    Deleted = 'deleted',
    Added = 'added'
}

export function ToggleSavedJobsResponseFromJSON(json: any): ToggleSavedJobsResponse {
    return ToggleSavedJobsResponseFromJSONTyped(json, false);
}

export function ToggleSavedJobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleSavedJobsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'ok': json['ok'],
    };
}

export function ToggleSavedJobsResponseToJSON(value?: ToggleSavedJobsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'ok': value.ok,
    };
}


