/* tslint:disable */
/* eslint-disable */
/**
 * JS-SS21 API Documentation
 * API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Address, AddressFromJSON, AddressFromJSONTyped, AddressToJSON, University, UniversityFromJSON, UniversityFromJSONTyped, UniversityToJSON } from './';

/**
 *
 * @export
 * @interface UpdateStudentDto
 */
export interface UpdateStudentDto {
	/**
	 * address field
	 * @type {Address}
	 * @memberof UpdateStudentDto
	 */
	address: Address;
	/**
	 * university object
	 * @type {University}
	 * @memberof UpdateStudentDto
	 */
	university: University;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateStudentDto
	 */
	email: string;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateStudentDto
	 */
	firstName: string;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateStudentDto
	 */
	lastName: string;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateStudentDto
	 */
	githubUrl: string;
	/**
	 *
	 * @type {number}
	 * @memberof UpdateStudentDto
	 */
	semester: number;
	/**
	 *
	 * @type {string[]}
	 * @memberof UpdateStudentDto
	 */
	skills: string[];
	/**
	 *
	 * @type {string[]}
	 * @memberof UpdateStudentDto
	 */
	languages: string[];
	/**
	 *
	 * @type {number}
	 * @memberof UpdateStudentDto
	 */
	yearsOfExperience: number;
	/**
	 *
	 * @type {Date}
	 * @memberof UpdateStudentDto
	 */
	fromAvailable: Date;
	/**
	 *
	 * @type {Date}
	 * @memberof UpdateStudentDto
	 */
	toAvailable: Date;
	/**
	 *
	 * @type {number}
	 * @memberof UpdateStudentDto
	 */
	workBasis: number;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateStudentDto
	 */
	workArea: string;
	/**
	 *
	 * @type {string}
	 * @memberof UpdateStudentDto
	 */
	description: string;
}

export function UpdateStudentDtoFromJSON(json: any): UpdateStudentDto {
	return UpdateStudentDtoFromJSONTyped(json, false);
}

export function UpdateStudentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStudentDto {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		address: AddressFromJSON(json['address']),
		university: UniversityFromJSON(json['university']),
		email: json['email'],
		firstName: json['firstName'],
		lastName: json['lastName'],
		githubUrl: json['githubUrl'],
		semester: json['semester'],
		skills: json['skills'],
		languages: json['languages'],
		yearsOfExperience: json['yearsOfExperience'],
		fromAvailable: new Date(json['fromAvailable']),
		toAvailable: new Date(json['toAvailable']),
		workBasis: json['workBasis'],
		workArea: json['workArea'],
		description: json['description'],
	};
}

export function UpdateStudentDtoToJSON(value?: UpdateStudentDto | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		address: AddressToJSON(value.address),
		university: UniversityToJSON(value.university),
		email: value.email,
		firstName: value.firstName,
		lastName: value.lastName,
		githubUrl: value.githubUrl,
		semester: value.semester,
		skills: value.skills,
		languages: value.languages,
		yearsOfExperience: value.yearsOfExperience,
		fromAvailable: value.fromAvailable.toISOString(),
		toAvailable: value.toAvailable.toISOString(),
		workBasis: value.workBasis,
		workArea: value.workArea,
		description: value.description,
	};
}
