name: Lint Pull Requests
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Upgrade npm to v7
        run: npm install -g npm@latest
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
