/**
 * JS-SS21 API Documentation
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address';
import { HttpFile } from '../http/http';

export class CompanyDto {
    /**
    * address field
    */
    'address': Address;
    'email': string;
    'name': string;
    'companyInfo': string;
    'homepage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "Address",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyInfo",
            "baseName": "company_info",
            "type": "string",
            "format": ""
        },
        {
            "name": "homepage",
            "baseName": "homepage",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CompanyDto.attributeTypeMap;
    }
    
    public constructor() {
    }
}

