/**
 * JS-SS21 API Documentation
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Job {
    'id': string;
    'publisherId': string;
    'contactMail': string;
    'jobName': string;
    'jobDescription': string;
    'jobQualifications': Array<string>;
    'skills': Array<string>;
    'workArea': string;
    'workBasis': number;
    'languages': Array<string>;
    'from': Date;
    'to': Date;
    'active': boolean;
    'requestedByStudents': Array<string>;
    'requestedIds': Array<string>;
    'finalAcceptedId': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "publisherId",
            "baseName": "publisher_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactMail",
            "baseName": "contactMail",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobName",
            "baseName": "jobName",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobDescription",
            "baseName": "jobDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobQualifications",
            "baseName": "jobQualifications",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "skills",
            "baseName": "skills",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "workArea",
            "baseName": "workArea",
            "type": "string",
            "format": ""
        },
        {
            "name": "workBasis",
            "baseName": "workBasis",
            "type": "number",
            "format": ""
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "requestedByStudents",
            "baseName": "requested_by_students",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "requestedIds",
            "baseName": "requested_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "finalAcceptedId",
            "baseName": "final_accepted_id",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Job.attributeTypeMap;
    }
    
    public constructor() {
    }
}

