/**
 * JS-SS21 API Documentation
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SearchJobDto {
    'searchString': string;
    'workArea': string;
    'workBasis': number;
    'languages': Array<string>;
    'skills': Array<string>;
    'from': Date;
    'to': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "searchString",
            "baseName": "searchString",
            "type": "string",
            "format": ""
        },
        {
            "name": "workArea",
            "baseName": "workArea",
            "type": "string",
            "format": ""
        },
        {
            "name": "workBasis",
            "baseName": "workBasis",
            "type": "number",
            "format": ""
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "skills",
            "baseName": "skills",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return SearchJobDto.attributeTypeMap;
    }
    
    public constructor() {
    }
}

