/**
 * JS-SS21 API Documentation
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class University {
    'name': string;
    'homepage': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "homepage",
            "baseName": "homepage",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return University.attributeTypeMap;
    }
    
    public constructor() {
    }
}

