/**
 * JS-SS21 API Documentation
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address';
import { University } from './University';
import { HttpFile } from '../http/http';

export class UpdateStudentDto {
    /**
    * address field
    */
    'address': Address;
    /**
    * university object
    */
    'university': University;
    'email': string;
    'firstName': string;
    'lastName': string;
    'semester': number;
    'skills': Array<string>;
    'languages': Array<string>;
    'yearsOfExperience': number;
    'fromAvailable': Date;
    'toAvailable': Date;
    'workBasis': number;
    'workArea': string;
    'description': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "Address",
            "format": ""
        },
        {
            "name": "university",
            "baseName": "university",
            "type": "University",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "semester",
            "baseName": "semester",
            "type": "number",
            "format": ""
        },
        {
            "name": "skills",
            "baseName": "skills",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "yearsOfExperience",
            "baseName": "yearsOfExperience",
            "type": "number",
            "format": ""
        },
        {
            "name": "fromAvailable",
            "baseName": "fromAvailable",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "toAvailable",
            "baseName": "toAvailable",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "workBasis",
            "baseName": "workBasis",
            "type": "number",
            "format": ""
        },
        {
            "name": "workArea",
            "baseName": "workArea",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateStudentDto.attributeTypeMap;
    }
    
    public constructor() {
    }
}

