/**
 * JS-SS21 API Documentation
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OneOfStudentCompany } from './OneOfStudentCompany';
import { HttpFile } from '../http/http';

export class UserResponse {
    /**
    * student or company
    */
    'userType': string;
    /**
    * Student entity
    */
    'userData': OneOfStudentCompany;
    /**
    * Jobs with company or only jobs (userType Company)
    */
    'assignedJobs': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userType",
            "baseName": "userType",
            "type": "string",
            "format": ""
        },
        {
            "name": "userData",
            "baseName": "userData",
            "type": "OneOfStudentCompany",
            "format": ""
        },
        {
            "name": "assignedJobs",
            "baseName": "assignedJobs",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

